package com.medicalSolutionsInc.enumerations.user;

public enum UserRole {

    // ======= TOP-LEVEL ADMINISTRATION =======
    SUPER_ADMIN,
    ADMIN,
    HOSPITAL_DIRECTOR,
    MEDICAL_DIRECTOR,
    CHIEF_MEDICAL_OFFICER,
    CHIEF_NURSING_OFFICER,
    CHIEF_OPERATIONS_OFFICER,
    CHIEF_FINANCIAL_OFFICER,
    CHIEF_TECHNOLOGY_OFFICER,
    CHIEF_COMPLIANCE_OFFICER,

    // ======= MEDICAL STAFF =======
    DOCTOR,
    SURGEON,
    RADIOLOGIST,
    ANESTHESIOLOGIST,
    DENTIST,
    PEDIATRICIAN,
    CARDIOLOGIST,
    NEUROLOGIST,
    PSYCHIATRIST,
    PATHOLOGIST,
    GENERAL_PRACTITIONER,
    CONSULTANT,

    // ======= NURSING & SUPPORT =======
    NURSE,
    HEAD_NURSE,
    NURSE_PRACTITIONER,
    MIDWIFE,
    MEDICAL_ASSISTANT,
    EMERGENCY_RESPONDER,
    PARAMEDIC,
    THERAPIST,
    PHYSIOTHERAPIST,
    OCCUPATIONAL_THERAPIST,
    RESPIRATORY_THERAPIST,

    // ======= DIAGNOSTICS & LAB =======
    LAB_TECHNICIAN,
    LAB_MANAGER,
    RADIOLOGY_TECHNICIAN,
    ULTRASOUND_TECHNICIAN,
    MRI_TECHNICIAN,
    CT_SCAN_TECHNICIAN,

    // ======= PHARMACY =======
    PHARMACIST,
    PHARMACY_TECHNICIAN,
    PHARMACY_MANAGER,

    // ======= FRONT DESK & PATIENT SERVICES =======
    RECEPTIONIST,
    PATIENT_COORDINATOR,
    FRONT_DESK_MANAGER,
    CUSTOMER_SERVICE_OFFICER,

    // ======= BILLING & FINANCE =======
    BILLING_SPECIALIST,
    CASHIER,
    ACCOUNTANT,
    FINANCE_MANAGER,
    INSURANCE_COORDINATOR,
    CLAIMS_OFFICER,

    // ======= IT & ENGINEERING =======
    IT_SUPPORT,
    IT_MANAGER,
    SOFTWARE_DEVELOPER,
    DEVOPS_ENGINEER,
    DATA_SCIENTIST,
    DATA_ANALYST,
    SYSTEM_ADMINISTRATOR,
    NETWORK_ENGINEER,
    CYBERSECURITY_ANALYST,
    QUALITY_ASSURANCE,

    // ======= HR & COMPLIANCE =======
    HR_MANAGER,
    HR_ASSISTANT,
    COMPLIANCE_OFFICER,
    TRAINING_COORDINATOR,

    // ======= OPERATIONS & FACILITY MANAGEMENT =======
    OPERATIONS_MANAGER,
    FACILITY_MANAGER,
    MAINTENANCE_TECHNICIAN,
    CLEANING_STAFF,
    SECURITY_OFFICER,
    TRANSPORT_DRIVER,

    // ======= WAREHOUSE & PROCUREMENT =======
    PROCUREMENT_OFFICER,
    SUPPLY_CHAIN_MANAGER,
    INVENTORY_MANAGER,
    STORE_KEEPER,

    // ======= EXTERNAL & COMMUNITY =======
    SOCIAL_WORKER,
    VOLUNTEER,
    COMMUNITY_HEALTH_WORKER,
    PUBLIC_HEALTH_OFFICER,

    // ======= PATIENT ROLE =======
    PATIENT
}

